options:
  env:
    - 'REGION_ID=europe-central2'
steps:
  # Install dependencies
  - name: node
    entrypoint: npm
    args: ['install']
    id: 'install'
    dir: 'gcp/nodejs-theaifam5'
  # Run unit tests
  - name: node
    entrypoint: npm
    args: ['run', 'unit-test']
    id: 'utest'
    dir: 'gcp/nodejs-theaifam5'
    waitFor: ['install']
  # Run integration tests
  - name: node
    entrypoint: npm
    args: ['run', 'integration-test']
    id: 'itest'
    dir: 'gcp/nodejs-theaifam5'
    waitFor: ['install']
  # Deploy function
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - functions
      - deploy
      - hello-theaifam5
      - --runtime=nodejs14
      - --trigger-http
      - --region=$REGION_ID
      - --memory=256MB      
      - --allow-unauthenticated
    id: 'deploy'
    dir: 'gcp/nodejs-theaifam5'
    waitFor: ['utest', 'itest']
  # Run system test
  - name: node
    entrypoint: npm
    env:
      - 'BASE_URL=https://$REGION_ID-$PROJECT_ID.cloudfunctions.net/'
    args: ['run', 'system-test']
    dir: 'gcp/nodejs-theaifam5'
    waitFor: ['deploy']
