steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - martin-hello-world
      - --runtime=dotnet3
      - --trigger-http
      - --region=europe-central2
      - --memory=256MB
      - --entry-point=HelloWorld.Function
      - --allow-unauthenticated
    id: "deploying-a-serverless-function#1"
    dir: "gcp/martin"
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - danes-test-func
      - --runtime=dotnet3
      - --trigger-http
      - --region=europe-central2
      - --memory=256MB
      - --entry-point=DanesTestFunc.Function
      - --allow-unauthenticated
    id: "deploying-a-serverless-function#2"
    dir: "gcp/dane"
  # Run tests and save to file
  - name: golang
    waitFor: ["-"]
    entrypoint: /bin/bash
    id: "go-testing"
    args: 
      - -c
      - |
        cd gcp/golang-marcel
        go get -u github.com/jstemmer/go-junit-report
        2>&1 go test -timeout 1m -v ./... | tee sponge.log
        /go/bin/go-junit-report -set-exit-code < sponge.log > ${SHORT_SHA}_test_log.xml
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["go-testing"]
    args:
      - functions
      - deploy
      - GoApi
      - --runtime=go113
      - --trigger-http
      - --region=us-central1
      - --memory=256MB
      - --allow-unauthenticated
    id: "deploying-a-serverless-function#3"
    dir: "gcp/christle"