steps:
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - martin-hello-world
      - --runtime=dotnet3
      - --trigger-http
      - --region=europe-central2
      - --memory=256MB
      - --entry-point=HelloWorld.Function
      - --allow-unauthenticated
    id: "deploying-a-serverless-function#1"
    dir: "gcp/martin"
  - name: "gcr.io/cloud-builders/gcloud"
    waitFor: ["-"]
    args:
      - functions
      - deploy
      - danes-test-func
      - --runtime=dotnet3
      - --trigger-http
      - --region=europe-central2
      - --memory=256MB
      - --entry-point=DanesTestFunc.Function
      - --allow-unauthenticated
    id: "deploying-a-serverless-function#2"
    dir: "gcp/dane"